pipeline:
  test:
    image: golang:1.6
    environment:
      - CGO_ENABLED=0
      - GOPATH=/drone
    commands:
      - make vet
      - make build
      - make test
  docker:
    storage_driver: overlay
    repo: plugins/drone-azure-storage
    tag: [ "latest" ]
    when:
      branch: release/0.4
      event: push

plugin:
  name: Azure Storage
  desc: Publish files and artifacts to Azure Storage
  type: publish
  image: plugins/drone-azure-storage
  labels:
    - azure
    - storage
