FROM plugins/base:linux-arm64

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" \
  org.label-schema.name="Drone Azure Storage" \
  org.label-schema.vendor="Drone.IO Community" \
  org.label-schema.schema-version="1.0"

RUN apk add --no-cache python py-pip build-base python-dev libffi-dev openssl-dev && \
  pip install -U pip && \
  pip install blobxfer==0.9.9.11

ADD release/linux/arm64/drone-azure-storage /bin/
ENTRYPOINT ["/bin/drone-azure-storage"]
