# escape=`
FROM plugins/base:windows-1803

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" `
  org.label-schema.name="Drone Azure Storage" `
  org.label-schema.vendor="Drone.IO Community" `
  org.label-schema.schema-version="1.0"

ADD release/windows/amd64/drone-azure-storage.exe C:/bin/drone-azure-storage.exe
ENTRYPOINT [ "C:\\bin\\drone-azure-storage.exe" ]
